/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evoddgame;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author kumar
 */
public class EveOddGame extends javax.swing.JFrame {
    
    static int score =0;
    static int count =0;
   
    Random r = new Random();
    int randomnum;
    
    
    
    public EveOddGame() {
        initComponents();

     randomnum = r.nextInt(100);
     Lebel1.setText(String.valueOf(randomnum));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnodd = new java.awt.Button();
        btneven = new java.awt.Button();
        Lebel2 = new javax.swing.JLabel();
        Lebel3 = new javax.swing.JLabel();
        Lebel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.setForeground(new java.awt.Color(51, 255, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("EvenOdd Game");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 204));

        btnodd.setBackground(new java.awt.Color(102, 255, 255));
        btnodd.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnodd.setLabel("Odd");
        btnodd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoddActionPerformed(evt);
            }
        });

        btneven.setBackground(new java.awt.Color(102, 204, 255));
        btneven.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btneven.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btneven.setLabel("Even");
        btneven.setName(""); // NOI18N
        btneven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnevenActionPerformed(evt);
            }
        });

        Lebel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        Lebel2.setText("Score");

        Lebel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        Lebel3.setForeground(new java.awt.Color(255, 0, 0));

        Lebel1.setBackground(new java.awt.Color(0, 0, 255));
        Lebel1.setFont(new java.awt.Font("Trebuchet MS", 1, 65)); // NOI18N
        Lebel1.setForeground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btneven, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lebel2))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(Lebel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnodd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lebel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Lebel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnodd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lebel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lebel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnoddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoddActionPerformed
        // TODO add your handling code here:
        
        count = count+1;
        int num = Integer.parseInt(Lebel1.getText());
        if(count==10){
            if(num%2!=0){
                score = score+1;
                Lebel3.setText(String.valueOf(score));
                randomnum = r.nextInt(100);
            }
            else {
                randomnum = r.nextInt(100);
                Lebel1.setText(String.valueOf(randomnum));
            }
            
            
            JOptionPane.showMessageDialog(this," Your score is : "+score+"/10");
            count =0;
            score =0;
            Lebel3.setText("");
            randomnum = r.nextInt(100);
            Lebel1.setText(String.valueOf(randomnum));
            
        }
        else {
            if(num%2!=0) {
                score = score+1;
                Lebel3.setText(String.valueOf(score));
                
                randomnum = r.nextInt(100);
                Lebel1.setText(String.valueOf(randomnum));
            }
            else {
                
                randomnum = r.nextInt(100);
                Lebel1.setText(String.valueOf(randomnum));
                
            }
        }
        
    }//GEN-LAST:event_btnoddActionPerformed

    private void btnevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnevenActionPerformed
        // TODO add your handling code here:
        count = count+1;
        int num = Integer.parseInt(Lebel1.getText());
        if(count==10){
            if(num%2==0){
                score = score +1;
                Lebel3.setText(String.valueOf(score));
                randomnum = r.nextInt(100);
            }
            else {
                randomnum = r.nextInt(100);
                Lebel1.setText(String.valueOf(randomnum));
            }
            
            
            JOptionPane.showMessageDialog(this," Your score is : "+score+"/10");
            count =0;
            score =0;
            Lebel3.setText("");
            randomnum = r.nextInt(100);
            Lebel1.setText(String.valueOf(randomnum));
            
        }
        else {
            if(num%2==0) {
                score = score+1;
                Lebel3.setText(String.valueOf(score));
                
                randomnum = r.nextInt(100);
                Lebel1.setText(String.valueOf(randomnum));
            }
            else {
                
                randomnum = r.nextInt(100);
                Lebel1.setText(String.valueOf(randomnum));
                
            }
        }
        
        
    }//GEN-LAST:event_btnevenActionPerformed

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EveOddGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lebel1;
    private javax.swing.JLabel Lebel2;
    private javax.swing.JLabel Lebel3;
    private java.awt.Button btneven;
    private java.awt.Button btnodd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
